language: python
python:
  - "3.9"
  - "3.9-dev"
  - "3.4"
  - "2.7"
# command to install dependencies
install:
  - pip install .  
  - pip install codecov
# command to run tests
script:
  - pytest # or py.test for Python versions 3.5 and below
  - coverage run -m unittest discover
after_success:
  - codecov
deploy:
    provider: pypi
    user: __token__
    password: $PYPI_SECRET
    on:
      python: "3.9"
      tags: true
