language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.5-dev"  # 3.5 development branch
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
# command to install dependencies
install:
  - pip install .  
  - pip install codecov
# command to run tests
script:
  - pytest # or py.test for Python versions 3.5 and below
  - coverage run -m unittest discover
after_success:
  - codecov
jobs:
  include:
    - stage: deploy pypi
      deploy:
          provider: pypi
          user: __token__
          password: $PYPI_SECRET
          on:
            tags: true
