language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.8-dev"
  - "nightly"  # nightly build
# command to install dependencies
install:
  - pip install .  
  - pip install codecov
# command to run tests
script:
  - pytest # or py.test for Python versions 3.5 and below
  - coverage run -m unittest discover
after_success:
  - codecov
jobs:
  include:
    - stage: deploy pypi
      deploy:
          provider: pypi
          user: __token__
          password: $PYPI_SECRET
          on:
            tags: true
